### ISSUE TITLE
Feature Request: point to a directory to serve files

### ISSUE THREAD

**Issue by tjkns94** [yungtravla/pyserver#2]
Have some kind of command line option or config where I can target the directory that I want to serve files/content at

**Comment by tjkns94** [comment]
also a config for the port number and proxy-ing and routes?

**Comment by buffermet** [comment]
The way it works now is you `cd` into your directory and then call `pyserver` and it will serve your current working directory

**Comment by buffermet** [comment]
I'll check for a port option

**Comment by tjkns94** [comment]
okay nice

**Comment by buffermet** [comment]
yo @thomasjulianstoelen I finally got around making the port option :)

**Comment by buffermet** [comment]
as far as proxying is concerned, this is really just meant as a shortcut for python's SimpleHTTPServer

There's much better, fully featured programs out there that can do that :)
